# Generated by Django 3.2.4 on 2021-06-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_maxid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maxid',
            name='LatestId',
        ),
        migrations.AddField(
            model_name='maxid',
            name='latestId',
            field=models.BigIntegerField(default=0, verbose_name='latestId'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='data',
            field=models.TextField(verbose_name='pair'),
        ),
    ]
