# Generated by Django 3.2.4 on 2021-06-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210612_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='data',
            new_name='pair',
        ),
    ]
