# Generated by Django 3.2.4 on 2021-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_maxid_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='heroId1',
            field=models.IntegerField(default=1, verbose_name='heroId1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='heroId2',
            field=models.IntegerField(default=1, verbose_name='heroId2'),
            preserve_default=False,
        ),
    ]
