# Generated by Django 3.2.4 on 2021-06-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210621_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='assists1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='assists2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='deaths1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='deaths2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='denies1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='denies2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='isVictory',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kills1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kills2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='lastHits1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='lastHits2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='networth1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='networth2',
        ),
    ]
