# Generated by Django 3.2.4 on 2021-06-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210621_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullData',
            fields=[
                ('data', models.TextField(verbose_name='data')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.match')),
            ],
        ),
        migrations.DeleteModel(
            name='MaxId',
        ),
    ]
